# Generated by Django 5.1.1 on 2024-10-01 17:41

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attractions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='img_attractions/')),
            ],
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('culture_name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='img_culture/')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='img_currency/')),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='img_games/')),
            ],
        ),
        migrations.CreateModel(
            name='HandCrafts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handcraft_name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='img_crafts/')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('offered_amenities', models.TextField()),
                ('laest', models.IntegerField(default=0)),
                ('short_period', models.IntegerField(default=1000)),
                ('medium_period', models.IntegerField(default=1500)),
                ('long_period', models.IntegerField(default=2000)),
                ('like', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kitchen', models.CharField(max_length=32)),
                ('category', models.CharField(max_length=32)),
                ('price_range', models.CharField(max_length=32)),
                ('specialized_menu', models.CharField(max_length=100)),
                ('meal_time', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('number_phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NationalClothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothes_name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='img_clothes/')),
            ],
        ),
        migrations.CreateModel(
            name='NationalFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationalfood_name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='img_nationalfood/')),
            ],
        ),
        migrations.CreateModel(
            name='NationalInstruments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='img_instruments/')),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('places_name', models.CharField(max_length=32)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AttractionsPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='att_photos', to='store.attractions')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HotelPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_hotel', to='store.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='KitchenPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kit_photos', to='store.kitchen')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='places',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.places'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.cart')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.hotel')),
                ('places', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.places')),
            ],
        ),
        migrations.AddField(
            model_name='attractions',
            name='att_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.places'),
        ),
        migrations.CreateModel(
            name='PlacesPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img_places/')),
                ('places', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places_photos', to='store.places')),
            ],
        ),
        migrations.AddField(
            model_name='places',
            name='region_places',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.region'),
        ),
        migrations.CreateModel(
            name='RegionFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=32)),
                ('include_food', models.CharField(max_length=64)),
                ('description_name', models.TextField()),
                ('description_food', models.TextField()),
                ('image', models.ImageField(upload_to='img_region_food/')),
                ('region_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_food', to='store.region')),
            ],
        ),
        migrations.CreateModel(
            name='RegionPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img_region/')),
                ('region_photos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_photos', to='store.region')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'Плохо'), (2, 'Удовлетворительно'), (3, 'Средне'), (4, 'Хорошо'), (5, 'Отлично')])),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('attractions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='att_reviews', to='store.attractions')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('places', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.places')),
            ],
        ),
        migrations.CreateModel(
            name='PhotosReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_review', to='store.review')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'Плохо'), (2, 'Удовлетворительно'), (3, 'Средне'), (4, 'Хорошо'), (5, 'Отлично')])),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hotels', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='store.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewKitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'Плохо'), (2, 'Удовлетворительно'), (3, 'Средне'), (4, 'Хорошо'), (5, 'Отлично')])),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kitchen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kitchen', to='store.kitchen')),
            ],
        ),
    ]
