# Generated by Django 5.1.1 on 2024-10-01 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='places',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.places'),
            preserve_default=False,
        ),
    ]
