# Generated by Django 5.1.1 on 2024-10-01 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_kitchen_places'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='attractions',
        ),
        migrations.CreateModel(
            name='ReviewAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'Плохо'), (2, 'Удовлетворительно'), (3, 'Средне'), (4, 'Хорошо'), (5, 'Отлично')])),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('attractions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='att_reviews', to='store.attractions')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
