# Generated by Django 5.1.1 on 2024-10-02 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_review_attractions_reviewattraction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='like',
        ),
    ]
