# Generated by Django 5.1.1 on 2024-10-02 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_hotel_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotosReviewAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_review', to='store.reviewattraction')),
            ],
        ),
        migrations.CreateModel(
            name='PhotosReviewHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_review', to='store.reviewhotel')),
            ],
        ),
        migrations.CreateModel(
            name='PhotosReviewKitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_review', to='store.reviewkitchen')),
            ],
        ),
    ]
