# Generated by Django 5.1.1 on 2024-10-07 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_hotel_bathroom_remove_hotel_bedroom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='laest',
        ),
    ]
