# Generated by Django 5.1.1 on 2024-10-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_photosreviewattraction_photosreviewhotel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='phone_number',
            field=models.IntegerField(default=996),
        ),
    ]
