# Generated by Django 5.1.1 on 2024-10-02 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_cartitem_kitchen_alter_hotel_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='attractions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.attractions'),
        ),
    ]
