# Generated by Django 5.1.1 on 2024-10-02 19:10

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_cartitem_attractions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchen',
            name='number_phone',
        ),
        migrations.RemoveField(
            model_name='regionfood',
            name='description_food',
        ),
        migrations.AddField(
            model_name='hotel',
            name='bathroom',
            field=models.CharField(blank=True, default=0, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='bedroom',
            field=models.CharField(blank=True, default=0, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='car_bikes',
            field=models.CharField(blank=True, default=0, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='pets_allow',
            field=models.CharField(blank=True, default=0, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='address',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kitchen',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='KG'),
        ),
        migrations.AlterField(
            model_name='regionfood',
            name='include_food',
            field=models.TextField(),
        ),
    ]
