# Generated by Django 5.1.1 on 2024-10-04 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_kitchen_number_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photosreviewattraction',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_review_attraction', to='store.reviewattraction'),
        ),
        migrations.AlterField(
            model_name='photosreviewhotel',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_review_hotel', to='store.reviewhotel'),
        ),
        migrations.AlterField(
            model_name='photosreviewkitchen',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_review_kitchen', to='store.reviewkitchen'),
        ),
    ]
