# Generated by Django 5.1.1 on 2024-10-04 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_photosreviewattraction_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reviewattraction',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reviewhotel',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reviewkitchen',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ReviewLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.reviewhotel')),
                ('places', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.review')),
            ],
        ),
    ]
