# Generated by Django 5.1.1 on 2024-10-04 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_userprofile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewhotel',
            old_name='hotels',
            new_name='hotel',
        ),
    ]
